"use client";

import { useEffect, useState, useRef } from "react";
import { useRouter } from "next/navigation";
import JoiningLetterTemplate from "@/components/documents/JoiningLetterTemplate";
import jsPDF from "jspdf";
import { toPng } from "html-to-image";

export default function StudentJoiningLetterPage() {
    const router = useRouter();
    const [user, setUser] = useState<{ id: string; name: string } | null>(null);
    const [letterData, setLetterData] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [isDownloading, setIsDownloading] = useState(false);
    const letterRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        const stored = sessionStorage.getItem("currentUser");
        if (stored) {
            const userData = JSON.parse(stored);
            setUser(userData);
            fetchLetter(userData.id);
        } else {
            router.push("/login");
        }
    }, [router]);

    const fetchLetter = async (userId: string) => {
        try {
            const res = await fetch(`/api/admin/documents/joining-letter?userId=${userId}`);
            const data = await res.json();
            if (data.success && data.letter) {
                setLetterData(data.letter);
            } else {
                setLetterData(null);
            }
        } catch (error) {
            console.error(error);
        } finally {
            setLoading(false);
        }
    };

    const formatDate = (dateString: string) => {
        if (!dateString) return "";
        return new Date(dateString).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    };

    const handleDownload = async () => {
        setIsDownloading(true);
        try {
            const { toPng } = await import('html-to-image');
            const jsPDF = (await import('jspdf')).default;

            if (letterRef.current) {
                const dataUrl = await toPng(letterRef.current, { quality: 1.0, pixelRatio: 3 });
                const pdf = new jsPDF('p', 'mm', 'a4');
                const imgProps = pdf.getImageProperties(dataUrl);
                const pdfWidth = pdf.internal.pageSize.getWidth();
                const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;

                pdf.addImage(dataUrl, 'PNG', 0, 0, pdfWidth, pdfHeight);
                pdf.save(`My_Joining_Letter.pdf`);
            }
        } catch (e) {
            console.error(e);
            alert("Failed to download PDF");
        } finally {
            setIsDownloading(false);
        }
    };

    if (loading) {
        return <div className="min-h-screen bg-background text-gold-theme flex items-center justify-center animate-pulse">Loading Document...</div>;
    }

    if (!letterData) {
        return (
            <div className="min-h-screen bg-background text-foreground p-8 flex flex-col items-center justify-center">
                <div className="bg-card/40 border border-theme p-8 rounded-xl text-center max-w-md">
                    <h1 className="text-2xl font-bold text-foreground mb-4">No Letter Issued Yet</h1>
                    <p className="text-muted-foreground mb-6">Your joining letter has not been generated by the administration yet. Please contact HR.</p>
                    <button onClick={() => router.push('/dashboard/student')} className="bg-foreground/10 hover:bg-foreground/20 px-6 py-2 rounded text-foreground font-bold transition-colors">
                        Back to Dashboard
                    </button>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-background text-foreground p-8">
            <header className="flex justify-between items-center mb-8 max-w-[1000px] mx-auto">
                <button onClick={() => router.push('/dashboard/student')} className="text-muted-foreground hover:text-gold-theme flex items-center gap-2 transition-colors">
                    ← Back to Dashboard
                </button>
                <div className="flex gap-4">
                    <button
                        onClick={handleDownload}
                        disabled={isDownloading}
                        className="bg-gold-theme hover:bg-gold-theme/90 text-black font-bold px-6 py-2 rounded transition-colors shadow-lg disabled:opacity-50"
                    >
                        {isDownloading ? "Downloading..." : "Download PDF"}
                    </button>
                </div>
            </header>

            <div className="flex justify-center overflow-auto pb-20">
                <div className="transform scale-90 origin-top">
                    <JoiningLetterTemplate
                        ref={letterRef}
                        formData={letterData}
                        formatDate={formatDate}
                        duration={(() => {
                            if (!letterData?.startDate || !letterData?.endDate) return "6 Months";
                            try {
                                const start = new Date(letterData.startDate);
                                const end = new Date(letterData.endDate);
                                const diffMonths = (end.getFullYear() - start.getFullYear()) * 12 + (end.getMonth() - start.getMonth());
                                return diffMonths > 0 ? `${diffMonths} Months` : "6 Months";
                            } catch (e) { return "6 Months"; }
                        })()}
                    />
                </div>
            </div>
        </div>
    );
}
